# Generated by Django 3.2 on 2022-02-02 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedChildPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Цвет ')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='createdchild/', verbose_name='Картинка')),
                ('style', models.CharField(max_length=128, verbose_name='свойство CSS')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'добавляем детеныша',
                'verbose_name_plural': 'добавляем детеныша',
            },
        ),
        migrations.CreateModel(
            name='TypePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Цвет ')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='type_page/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Тип странички',
                'verbose_name_plural': 'Тип странички',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ChangePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('type_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_page', to='create_page.typepages', verbose_name='Тип странички')),
            ],
            options={
                'verbose_name': 'Выбрать страницу',
                'verbose_name_plural': 'Выбрать страницу',
            },
        ),
    ]
