# Generated by Django 3.2 on 2022-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepage',
            name='child_create',
            field=models.ManyToManyField(to='create_page.CreatedChildPage', verbose_name='детеныш'),
        ),
    ]
