# Generated by Django 3.2 on 2022-02-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_page', '0002_changepage_child_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepages',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название '),
        ),
    ]
