# Generated by Django 3.2 on 2022-02-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_page', '0003_alter_typepages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTwo',
            fields=[
                ('createdchildpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='create_page.createdchildpage')),
                ('nametwo', models.CharField(max_length=128, verbose_name='Название ')),
                ('slugtwo', models.SlugField(max_length=64, unique=True)),
                ('imagetwo', models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='createdchildtwo/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'добавляем детеныша',
                'verbose_name_plural': 'добавляем детеныша',
            },
            bases=('create_page.createdchildpage',),
        ),
        migrations.AlterField(
            model_name='createdchildpage',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название '),
        ),
    ]
