# Generated by Django 3.2 on 2022-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_page', '0004_auto_20220202_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createtwo',
            options={'verbose_name': 'добавляем детеныша2', 'verbose_name_plural': 'добавляем детеныша2'},
        ),
        migrations.AddField(
            model_name='changepage',
            name='parent',
            field=models.CharField(blank=True, max_length=128, verbose_name='Кто родитель'),
        ),
    ]
