# Generated by Django 3.2 on 2022-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Цвет ')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='colorpages/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Цвет странички',
                'verbose_name_plural': 'Цвет странички',
                'ordering': ('-name',),
            },
        ),
    ]
