# Generated by Django 3.2 on 2022-01-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorpage', '0002_changecolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeColor',
        ),
    ]
