# Generated by Django 3.2 on 2022-01-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colorpage', '0003_delete_changecolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='colorpage.colorpages')),
            ],
            options={
                'verbose_name': 'Выбрать цвет',
                'verbose_name_plural': 'Выбрать цвет',
            },
        ),
    ]
