# Generated by Django 3.2 on 2022-01-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorpage', '0005_auto_20220128_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changecolor',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название страницы'),
        ),
    ]
