# Generated by Django 3.2 on 2022-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Бренды')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='brands/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='category/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='promo/', verbose_name='Картинка')),
                ('promo_type', models.CharField(max_length=128, verbose_name='Тип рекламы')),
                ('description', models.TextField(verbose_name='Опсание')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='Начало')),
                ('end_time', models.DateField(null=True, verbose_name='Конец')),
                ('available', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
    ]
