# Generated by Django 3.2 on 2022-01-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Реклама акции', 'verbose_name_plural': 'Реклама акции'},
        ),
    ]
