# Generated by Django 3.2 on 2022-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220123_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='start_time',
            field=models.DateField(null=True, verbose_name='Начало'),
        ),
    ]
