# Generated by Django 3.2 on 2022-01-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_promo_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('model', models.CharField(max_length=128, verbose_name='Модель')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('color', models.CharField(max_length=30)),
                ('warranty', models.IntegerField()),
                ('count', models.IntegerField()),
                ('brand_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.brands')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('promo', models.ManyToManyField(to='shop.Promo')),
            ],
            options={
                'verbose_name': 'Все товары',
                'verbose_name_plural': 'Все товары',
            },
        ),
    ]
