# Generated by Django 3.2 on 2022-01-25 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_dishwasher_notebook_tv_vacuumcleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishwasher',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='dishwasher/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='dishwasher',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='notebook/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='tv/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='tv',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='vacuumcleaner',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='vacuumcleaner/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='vacuumcleaner',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='brands/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='category/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.brands', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='promo',
            field=models.ManyToManyField(to='shop.Promo', verbose_name='Реклама акции'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='promo/', verbose_name='Картинка'),
        ),
    ]
