# Generated by Django 3.2 on 2022-01-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220125_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishwasher',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tv',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='vacuumcleaner',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
