# Generated by Django 3.2 on 2022-01-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220125_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishwasher',
            name='energy_saving_class',
            field=models.CharField(default='A+', max_length=2, verbose_name='Энергопотребление'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='display',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Экран'),
        ),
    ]
