# Generated by Django 3.2 on 2022-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220125_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='display',
            field=models.DecimalField(decimal_places=3, max_digits=3, verbose_name='Экран'),
        ),
    ]
