# Generated by Django 3.2 on 2022-01-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_notebook_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='display',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Экран'),
        ),
    ]
