# Generated by Django 3.2 on 2022-01-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_tv_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, default='user_default_profile.jpg', null=True, upload_to='clothes/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Взрослая одежда',
                'verbose_name_plural': 'Взрослая одежда',
            },
            bases=('shop.item',),
        ),
        migrations.AlterField(
            model_name='tv',
            name='display_type',
            field=models.CharField(max_length=8, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='smart_tv',
            field=models.BooleanField(verbose_name='SmartTV'),
        ),
    ]
