# Generated by Django 3.2 on 2022-01-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220125_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'verbose_name': 'Ноутбуки и ПК', 'verbose_name_plural': 'Ноутбуки и ПК'},
        ),
    ]
